export const baseRemoteHost='0.0.0.0'
export const baseLocalHost='localhost'
export const proxyRemoteUrl='http://www.miaojiangjiang.com:90'
export const proxyLocalUrl='http://www.miaojiangjiang.com:90'
// export const proxyLocalUrl='http://localhost:8081'
